name: 02 trigger events exploartions 
on:
  workflow_dispatch: 

jobs:
  first-job:
    name: Start job one 
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by ${{ github.event_name }}"
